server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/adc123321/config_server.git #配置git服务地址
          username: 1042732167@qq.com #配置git用户名
          password: qwert12345 #配置git密码
          search-paths:
            - course
      label: master